### ISSUE TITLE
feat: 마이페이지 수정된 요구사항 반영

### ISSUE THREAD

**Issue by rudeh1253** [team-HF/HF_backend#105]
# 개요
마이페이지 기능 중 변경된 요구사항을 반영하기 위한 마이페이지 기능 추가 개발

# TODO
- [x] 소셜 로그인 시 소셜 로그인 서비스에서 사용자 이름까지 가져오기 구현
- [x] 매칭 불러오기 페이징 구현
- [x] 매칭 중단 상태 추가 
- [x] 운동 스타일은 option 값으로 설
- [x] 운동 레벨 구현
  - 운동 레벨은 매칭 횟수에 따른 레벨업 정책 참조
- [x] 새싹 레벨 5단계에 도달할 경우에 운동 레벨 변경 가능
