### ISSUE TITLE
refactor: 에러 코드 관련 리팩토링

### ISSUE THREAD

**Issue by rudeh1253** [team-HF/HF_backend#120]
# 개요
에러 코드 통일에 따라 변경된 에러 코드를 반영
또한 Error response에 detail 내용을 넘길 수 있도록 리팩토링

# TODO
- [ ] 문서에 있는 에러 코드 반영
- 에러 코드 관련 피드백 반영
  - [ ] 에러 코드 재사용, detail 필드를 추가해 예외별 명시
  - [ ] com.hf.healthfriend.global.exception.ErrorCode에서 각 컴포넌트에 종속적인 에러코드를 따로 빼기
  - [ ] 에러 코드 관련된 enum이 공통적으로 implements할 수 있는 공통 인터페이스 정의
- [ ] ```BasicErrorResponse``` 리팩토링 (detail 필드 추가)
