### ISSUE TITLE
feat: 채팅 기능 구현

### ISSUE THREAD

**Issue by rudeh1253** [team-HF/HF_backend#136]
# 개요
기본적인 채팅 기능 구현. 웹소켓, MongoDB를 활용

## TODO
- [ ] 채팅 관련 Entity 정의
- [ ] 채팅 CRUD 작성
  - [ ] MongoDB 연동
- [ ] 웹소켓을 활용한 양방향 통신 구현
