### ISSUE TITLE
Test: 누락된 테스트 코드 추가

### ISSUE THREAD

**Issue by rudeh1253** [team-HF/HF_backend#17]
## 개요

각 컴포넌트별로 테스트 코드를 추가한다.

## TODO
- [x] Spring Security 부분 테스트 코드 추가
- [x] MemberService 테스트 코드 추가
- [x] member API 테스트 추가 (MockMVC)
