### ISSUE TITLE
Chore: 로드밸런서 사용을 위한 Actuator 설정

### ISSUE THREAD

**Issue by rudeh1253** [team-HF/HF_backend#27]
## 개요
로드밸런서를 사용하게 되면 로드밸런서에서 일정 시간마다 Health Check 요청을 보낼 것이다. 이때 Health Check용 Endpoint가 필요한데, Actuator의 /health endpoint를 개방하면 될 것이다.

## TODO
- [x] Actuator /health endpoint 개방
- [x] /actuator/health에 대한 인증/인가 로직 off
- [x] 헬스 체크에 대한 Logging 고려

**Comment by rudeh1253** [comment]
PR #99
