### ISSUE TITLE
feat: 좋아요 기능 구현

### ISSUE THREAD

**Issue by rudeh1253** [team-HF/HF_backend#42]
# 개요
커뮤니티 기능 중 좋아요 기능을 구현한다.

# TODO
- [x] 좋아요 관련 인터페이스 정의
- [x] 좋아요 관련 테스트 코드 작성
- [x] 좋아요 관련 인터페이스를 구현한 Bean 작성
- [x] API 테스트 코드 작성
- [x] API 구현

# 추가사항
좋아요 관련 성능을 어떻게 개선할지 고민해야 한다.
