### ISSUE TITLE
feat(mypage): 기획 변경사항/추가사항 반영

### ISSUE THREAD

**Issue by rudeh1253** [team-HF/HF_backend#61]
# 개요
마이페이지 기능 중에서 기획 변경사항/추가사항 (정책 등)을 반영하여 구현한다.

# TODO
### Request Parameter 검증
- [x] 닉네임 최대 8글자 입력 가능
- [x] 생년월일은 현재보다 빠르게
- [x] 휴대전화 형식 검증
- [x] 한 줄 소개 최대 500글자 제
### 정책 변경 반영
- [x] members 엔티티에 휴대전화 attribute 추가
- [x] members 엔티티에 휴대전화 인증 여부 attribute 추가 (우선 무조건 FALSE로 한 다음에 휴대전화 인증 기능이 구현되면 그때부터 유효한 데이터가 되도록 함)
- [x] members 엔티티에 이름 attribute 추가
- [x] members 에닡티에 현재 위치 attribute 추가 (OOO시 OO구까지)

#### 변경 가능 / 변경 불가
- [x] 프사 변경 가능
- [x] 이름 변경 불가
- [x] 닉네임 변경 불가
- [x] 현재위치 변경 가능
- [x] 운동 스타일:
  - 고수 -> 새싹 [변경불가]
  - 새싹 -> 고수 [매칭 횟수가 10회 이상일 시 변경 가능]
  - 이외 운동 스타일은 맘껏 변경 가능
- [x] 경력 및 수상사항 변경 가능
