### ISSUE TITLE
feat: 검색 API

### ISSUE THREAD

**Issue by dlrkdus** [team-HF/HF_backend#64]
# 개요 
- 검색 API 
- 검색 조회 API
# TODO
- [x] - 검색 API 
  - [x]   최근 검색 6개 
  - [x]   최근 검색 기록 삭제 api 
- [x]   검색 조회 API 
  - [x]   프로필 (프사, 한줄소개, 팔로워) 개수 및 목록 반환
  - [x]   필터링 (프로필, 게시)
