### ISSUE TITLE
refactor: 프론트에서 S3로 직접 파일을 업로드하는 방식으로 변경

### ISSUE THREAD

**Issue by rudeh1253** [team-HF/HF_backend#96]
# 개요
프론트에서 S3로 직접 파일을 업로드함에 따라 백엔드에서는 파일을 처리하지 않음.
이에 따라 백엔드에서 파일을 처리하는 로직을 제거하고 프론트로 AWS S3 presigned URL을 반환하는 로직 추가
로컬 환경에서는 로컬에 파일을 저장하고 배포 시 S3로 파일을 업로드하도록 구현

# TODO
- [x] 파일 처리 로직 수정
- [x] presigned URL 응답에 추가
- [x] SpecController와 MemberController 병합
